<?php

/**
* Generated By GZeinNumerCodeGenerator
* www.github.com/gzeinnumer
* at 2022-10-28 09:02:08
* zip name 20221028090208_examples_v5_QPAq16AVFz.zip
*/

namespace App\Http\Controllers\API;

use App\Http\Resources\ExamplesV5Resource;
use App\Models\API\ExamplesV5Model;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;

class ExamplesV5Controller extends BaseController
{
    /*
    {
        "name" : ""
    }
    */
    //localhost:8000/api/examplesv5/insert
    public function insert(Request $r)
    {
        try {
            //to validate duplicate data
            //change activeValidateDuplicateData to true, if you want to validate 
            //if mobile sent duplicate data
            //add "created_at" : "2022-08-04 16:08:09" to json
            /*
            {
                "object1" : "data 1",
                "object2" : "data 2",
                "created_at" : "2022-08-04 16:08:09" // current time
            }
            */

            $activeValidateDuplicateData = false;
            if($activeValidateDuplicateData){
                $data = ExamplesV5Model::where([
                    "id" => $r->id,\n                    "name" => $r->name,\n                    "created_at" => $r->created_at,\n                    "updated_at" => $r->updated_at,\n                ])->first();
                if ($data != null) {
                    $apiResponse = $this->getApiResponse(1);
                    return $this->responseSuccess($apiResponse);
                }
            }

            $input = array(
                'name' => 'required|string|min:1',
            );

            $validator = Validator::make($r->all(), $input);

            if ($validator->fails()) {
                $apiResponse = $this->getApiResponse(0);
                $apiResponse->message = $validator->getMessageBag();
                return $this->responseFailed($apiResponse);
            }

            DB::beginTransaction();

            $data = new ExamplesV5Model();
            $data->name = $r->name;
            $data->save();

            DB::commit();

            $apiResponse = $this->getApiResponse(1);
            return $this->responseSuccess($apiResponse);
        } catch (\Throwable $th) {
            DB::rollBack();
            return $this->responseError($th);
        }
    }

    //localhost:8000/api/examplesv5/all
    public function all()
    {
        try {
            $data = ExamplesV5Model::all();

            return $this->toList(ExamplesV5Resource::collection($data), 1, 0);
        } catch (\Throwable $th) {
            return $this->responseError($th);
        }
    }

    //http://localhost:8000/api/examplesv5/paging?limit=10&page=1&start_date=2023-01-01&end_date=2023-01-01
    public function paging(Request $r)
    {
        try {
            $limit = $r->limit ? $r->limit : 10;
            $page = $r->page ? $r->page : 1;
            $start_date = $r->start_date;
            $end_date = $r->end_date;

            $query = DB::table('examples_v5');

            if ($start_date) {
                $query = $query->wherebetween("examples_v5.created_at", array($start_date . " 00:00:00", $end_date . " 23:59:59"));
            }

            $dataParsing = $query;

            return $this->toPaging(
                1,
                $dataParsing,
                $limit,
                $page
            );
        } catch (\Throwable $th) {
            return $this->responseError($th);
        }
    }

    /*
    {
        "name" : ""
    }
    */
    //localhost:8000/api/examplesv5/update/1
    public function update(Request $r, $id)
    {
        try {
            $input = array(
                'name' => 'required|string|min:1',
            );

            $validator = Validator::make($r->all(), $input);

            if ($validator->fails()) {
                $apiResponse = $this->getApiResponse(0);
                $apiResponse->message = $validator->getMessageBag();
                return $this->responseFailed($apiResponse);
            }

            DB::beginTransaction();

            $data = ExamplesV5Model::find($id);
            $data->name = $r->name;
            $data->save();

            DB::commit();

            $apiResponse = $this->getApiResponse(1);
            return $this->responseSuccess($apiResponse);
        } catch (\Throwable $th) {
            DB::rollBack();
            return $this->responseError($th);
        }
    }

    //localhost:8000/api/examplesv5/delete/1
    public function delete($id)
    {
        try {
            $data = ExamplesV5Model::find($id);

            DB::beginTransaction();

            $data->delete();

            DB::commit();

            $apiResponse = $this->getApiResponse(1);
            return $this->responseSuccess($apiResponse);
        } catch (\Throwable $th) {
            return $this->responseError($th);
        }
    }

    //localhost:8000/api/examplesv5/find/1
    public function find($id)
    {
        try {
            $data = ExamplesV5Model::find($id);

            return $this->toObject(new ExamplesV5Resource($data), 1, 0);
        } catch (\Throwable $th) {
            return $this->responseError($th);
        }
    }
}
