<?php

/**
* Generated By GZeinNumerCodeGenerator
* www.github.com/gzeinnumer
* at 2022-10-28 09:02:08
* zip name 20221028090208_examples_v5_QPAq16AVFz.zip
*/

namespace App\Http\Resources;

use Carbon\Carbon;
use Illuminate\Http\Resources\Json\JsonResource;

class ExamplesV5Resource extends JsonResource
{
    /**
     *   new ExamplesV5Resource(object)
     *   ExamplesV5Resource::collection([])
     */
    public function toArray($request)
    {
        return [
            'id' => $this->id,
            'name' => $this->name,
            'created_at' => Carbon::parse($this->created_at)->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::parse($this->updated_at)->format('Y-m-d H:i:s'),
        ];
    }
}
