<?php

/**
* Generated By GZeinNumerCodeGenerator
* www.github.com/gzeinnumer
* at 2022-10-28 09:02:08
* zip name 20221028090208_examples_v5_QPAq16AVFz.zip
*/

namespace App\Models\API;

use App\MyApp;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ExamplesV5Model extends Model
{
    use HasFactory;
    protected $table = "examples_v5";
    protected $fillable = ['name'];
    protected $casts = [
        'created_at'  => 'datetime:Y-m-d H:i:s',
        'updated_at' => 'datetime:Y-m-d H:i:s',
    ];
}
